config/routes.rb
Rails.application.routes.draw do
 

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :courses do
  resources :lectures
end
  resources :lectures do
  	member do
    post :spam
    put "like", to: "lectures#upvote"
    put "dislike", to: "lectures#downvote"
  end
  resources :comments
end

  devise_for :users, controllers: { registrations: "users/registrations" }
  # devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord

	belongs_to :user ,required: false
	belongs_to :lecture ,required: false

end

app/models/course.rb
class Course < ApplicationRecord

	has_many :lectures, dependent: :destroy
	belongs_to :user , required: false

end

app/models/lecture.rb
class Lecture < ApplicationRecord
	
	mount_uploader :attachment, AttachmentUploader
	belongs_to :course ,required: false
	has_and_belongs_to_many :users ,required: false
	has_many :comments, dependent: :destroy
	acts_as_votable

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :image, ImageUploader 
  validates :name, :image, presence: true
      
  enum gender: {male: 0,female: 1,any: 2}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :courses, dependent: :destroy
  has_and_belongs_to_many :lectures, dependent: :destroy
  has_many :comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected  
    def after_sign_in_path_for(resource)
     '/courses'
    end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base
  
  before_action :authenticate_user!,only: [:new ,:edit, :destroy]

  def index
    @lecture = Lecture.find(params[:lecture_id])
    @comments = @lecture.comments
  end

  def new
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.build
  end

  def create
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.create(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to lecture_comments_path
  end

  def edit
    @lecture = Lecture.find(params[:lecture_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.find(params[:id])
    @comment.update_attributes(comment_params)
    redirect_to([@comment.lecture, @comment], :notice => 'Comment was successfully updated.')   
  end

  def destroy
    @lecture = Lecture.find(params[:lecture_id])
    @comment = @lecture.comments.find(params[:id])
    @comment.destroy
    redirect_to lecture_comments_path
  end
  
  private

  def comment_params
    params.require(:comment).permit(:text ,:lecture_id ,:user_id)
  end
  
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
	
  before_action :authenticate_user!,only: [:new ,:edit, :destroy]

  def create
    @course = current_user.courses.create(course_params)
    @course.save
    redirect_to courses_path
  end
 
  private

    def course_params
      params.require(:course).permit(:title ,:user_id)
    end
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base

  before_action :authenticate_user!,only: [:spam, :upvote, :downvote, :new ,:edit, :destroy]

  def spam
    @lecture = Lecture.find(params[:id])
    current_user.lectures << Lecture.find(params[:id])
    redirect_to lecture_path(@lecture)
  end 

  def upvote 
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    redirect_to lecture_path(@lecture)
  end  

  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_by current_user
    redirect_to lecture_path(@lecture)
  end

  def index
  	@course = Course.find(params[:course_id])
  	@lectures = @course.lectures
  end
	
  def new
    @course = Course.find(params[:course_id])
    @lecture = @course.lectures.build
  end

  def create
    @course = Course.find(params[:course_id])
    @lecture = @course.lectures.create(lecture_params)
    @lecture.user_id = current_user.id
    @lecture.save
    redirect_to course_lectures_path
  end

  def show
    @lecture = Lecture.find(params[:id])
    @users = Lecture.find(params[:id]).users
    @ids = @users.ids
  end
    
  def edit
    @course = Course.find(params[:course_id])
    @lecture = Lecture.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:course_id])
    @lecture = Lecture.find(params[:id])
    @lecture.destroy
    redirect_to course_lectures_path
  end
  
  private
   
    def lecture_params
      params.require(:lecture).permit(:content, :attachment, :course_id ,:user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # Override the action you want here.
  protected

  def after_sign_up_path_for(resource)
    '/courses' # Or :prefix_to_your_route
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def sign_up_params
    params.require(:user).permit(:name, :email, :DOB, :gender, :image, :password, :password_confirmation)
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/comments/_form.html.erb
<%= form_for([@comment.lecture, @comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_field :text, id: :comment_text %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', lecture_comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Lecture</th>
      <th>User</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.text %></td>
        <td><%= comment.lecture_id %></td>
        <td><%= User.find(comment.user_id).name %></td>
        <% if((current_user) && (current_user.id == comment.user_id)) %>
        <td><%= link_to 'Edit',  edit_lecture_comment_path(comment.lecture , comment) %></td>
        <td><%= link_to 'Destroy', [comment.lecture , comment] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if((current_user)) %>
<%= link_to 'New Comment', new_lecture_comment_path %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', lecture_comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @comment.text %>
</p>

<p>
  <strong>Lecture:</strong>
  <%= @comment.lecture_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>
<% if((current_user) && (current_user.id == @comment.user_id)) %>
<%= link_to 'Edit', edit_lecture_comment_path(@comment) %> |
<% end %>
<%= link_to 'Back', lecture_comments_path %>

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>
      
      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :course_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= User.find(course.user_id).name %></td>
        <td><%= link_to 'Show', course %></td>
        <% if((current_user) && (current_user.id == course.user_id)) %>
        <td><%= link_to 'Edit', edit_course_path(course) %></td>
        <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if((current_user)) %>
<%= link_to 'New Course', new_course_path %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>
<p>
	<%= link_to "Lectures", course_lectures_path(course_id: @course.id) %>
</p>
<% if((current_user) && (current_user.id == @course.user_id)) %>
<%= link_to 'Edit', edit_course_path(@course) %> | 
<% end %> 
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MOOC</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lectures/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<%= form_for([@lecture.course, @lecture]) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content, :class => 'ckeditor' %> 
  </div>

  <div class="field">
    <%= form.label :attachment %>
    <%= form.file_field :attachment, id: :lecture_attachment %>
  </div>

 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', course_lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Attachment</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= raw(lecture.content) %></td>
        <td><%= link_to "Download file", lecture.attachment_url %></td>       
        <td><%= lecture.course.title %></td>
        <td><%= link_to 'Show',  lecture %></td>
        <% if((current_user) && (current_user.id == lecture.user_id)) %>
        <td><%= link_to 'Edit',  edit_course_lecture_path(lecture.course , lecture) %></td>
        <td><%= link_to 'Destroy', [lecture.course , lecture] , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if((current_user)) %>
  <%= link_to 'New Lecture', new_course_lecture_path %>
<% end %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', course_lectures_path %>

app/views/lectures/show.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= raw(@lecture.content) %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= link_to "Download file", @lecture.attachment_url %>
</p>

<p>
  <strong>Course:</strong>
  <%= @lecture.course_id %>
</p>
<%= link_to like_lecture_path(@lecture), method: :put do %>
  Like
  <%= @lecture.get_upvotes.size %>
<% end %>

<%= link_to dislike_lecture_path(@lecture), method: :put do %>
  Dislike
  <%= @lecture.get_downvotes.size %>
<% end %>


<% if((current_user) && !(@ids.include? current_user.id )) %>
<%= link_to 'Spam',spam_lecture_path(@lecture) , method: :post %>
<% end %>

<p>
	<%= link_to "Comments", lecture_comments_path(lecture_id: @lecture.id) %>
</p>

<% if((current_user) && (current_user.id == @lecture.user_id)) %>
<%= link_to 'Edit', edit_course_lecture_path(@lecture) %> |
<% end %>
<%= link_to 'Back', course_lectures_path(@lecture.course) %>